version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  echo_hello: # this can be any name you choose
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: echo_hello
          command: |
            echo hello

  echo_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: echo_world
          command: |
            echo world

workflows:
  test_my_app:
    jobs:
      - welcome/run
      - echo_hello
      - echo_world:
          requires:
            - echo_hello # only deploy if the echo_hello job has completed
